### ISSUE TITLE
Suggestion: Add Bug Report Issue Template?

### ISSUE THREAD

**Issue by Alex-Au1** [nhok0169/Anime-Game-Remap#22]
## Story
Some reported issues on both the mod site and on Github (eg. https://github.com/nhok0169/Fix-Raiden-Boss/issues/21) are not really bugs, but just **false alerts** of the user not installing the latest version of the fix.

## Suggested Solution
Provide the user with some pre-requisite checks before they report some issue on Github

## Suggested Bug Report Template
(inspired by [issues from yt-dlp](https://github.com/yt-dlp/yt-dlp/issues) )

### Checklist
- [x] #23
- [x] I have searched [issues on Github](https://github.com/nhok0169/Fix-Raiden-Boss/issues) **including closed ones** and  [issues on the mod site](https://gamebanana.com/tuts/15633) for similar issues. DO NOT post duplicates.
- [x] I included the **entire log** (as a screenshot or text) of my run of the fix

## How to make issue template

[More details here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)

### Step 1.
On your Github Repository, go to `Insights` --> `Community Standards`

### Step 2.
Click on **add** button by `issue templates`

![image](https://github.com/nhok0169/Fix-Raiden-Boss/assets/45087631/7f551961-ad5c-4f0d-9969-f9b576158c58)

### Step 3.
Click on the `add template dropdown` and select `Bug Report` (or any other issue template you want to make)

![image](https://github.com/nhok0169/Fix-Raiden-Boss/assets/45087631/d7096f2a-ba4b-4de3-90ca-e1ed52f96675)

### Step 4.
Click on `Preview and Edit` button and click the "pencil" icon. Then add whatever change you want to the template
![image](https://github.com/nhok0169/Fix-Raiden-Boss/assets/45087631/95e1baa0-b3a1-4a61-a3e2-c8f34fb900ed)

### Step 5.
Click on `propose changes` and commit the changes

**Comment by Alex-Au1** [comment]
I don't have permissions to add issues template for you since this is not my repo.

So you will have to do it on your own.

**Comment by nhok0169** [comment]
okay i will add it

**Comment by nhok0169** [comment]
shiet bro used white github
it hurt my eyes after night jobs so bad

**Comment by Alex-Au1** [comment]
lollol :stuck_out_tongue_closed_eyes: 

Its nostalgia to the time I code using [Replit](https://replit.com/) (when it first came out) and [Atom](https://github.com/atom/atom) ([RIP Atom 2022...:cry:](https://github.blog/2022-06-08-sunsetting-atom/))

**Comment by nhok0169** [comment]
ok now i got f*ck up when try copy yt-dlp code lmao

**Comment by Alex-Au1** [comment]
I think this pull request should fix the .yml code: https://github.com/nhok0169/Fix-Raiden-Boss/pull/24

(I just tested the code on one of my inactive repos)
![image](https://github.com/nhok0169/Fix-Raiden-Boss/assets/45087631/d30ddaab-ace5-483a-9ef9-f21aaac7a6b1)
